version: '3.8'

services:
  app:
    image: stevenbachimont/monsite:latest
    container_name: monsite
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000/tcp"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge