version: '3.8'

services:
  app:
    build: .
    container_name: SB/laLigneArgentique
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000/tcp"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge