version: '3.8'

services:
  app:
    build: .
    container_name: monsites
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000/tcp"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      # Variables Stripe (optionnelles - peuvent être définies dans .env)
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY:-}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge