name: Déploiement Docker sur VPS

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit

  deploy:
    runs-on: ubuntu-latest
    needs: test # Le déploiement ne se lance que si les tests passent

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Le fichier .env est géré directement sur le VPS

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/monsite:latest
          platforms: linux/amd64
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Déployer sur le VPS (pull + restart)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /root/monsite
            # Le fichier .env existe déjà sur le VPS, pas besoin de le recréer
            docker-compose pull
            docker-compose up -d --force-recreate
            
            # Nettoyer les images Docker inutilisées
            echo "🧹 Nettoyage des images Docker inutilisées..."
            docker image prune -f
            docker system prune -f --volumes
            
            # Supprimer spécifiquement les anciennes images monsite (garder seulement la dernière)
            echo "🗑️ Suppression des anciennes images monsite..."
            docker images "stevenbachimont/monsite" --format "table {{.Repository}}:{{.Tag}}\t{{.ID}}\t{{.CreatedAt}}" | tail -n +2 | head -n -1 | awk '{print $2}' | xargs -r docker rmi -f || true
            
            echo "✅ Nettoyage terminé" 