name: Déploiement Documentation GitHub Pages

on:
  push:
    branches:
      - main
      - steven2
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

  # Permet de déclencher manuellement le déploiement
  workflow_dispatch:

# Permissions pour GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Empêche les déploiements concurrents
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job pour construire la documentation
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérifier la structure de la documentation
        run: |
          echo "📁 Vérification de la structure de la documentation..."
          ls -la docs/
          if [ ! -f "docs/index.html" ]; then
            echo "❌ Erreur: docs/index.html n'existe pas"
            exit 1
          fi
          echo "✅ Structure de documentation valide"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  # Job pour déployer sur GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
